---
title: "write_validate_dp"
author: "Julia Wiel"
date: "`r Sys.Date()`"
output: "camtrap DP"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(here)
library(frictionless)
library(camtrapdp)
```

# Import tables from coat_to_camtrapdp.Rmd

```{r}
# Read the three tables
deployments <- read.csv(here::here("interim", "deployments.csv"))
media <- read.csv(here::here("interim", "media.csv"))
observations <- read.csv(here::here("interim", "observations.csv"))
```


# Create metadata package

```{r}
properties <-
  frictionless::create_package() %>%
  add_resource(resource_name = "deployments", data = deployments, schema = "https://raw.githubusercontent.com/tdwg/camtrap-dp/1.0.2/deployments-table-schema.json") %>%
  add_resource(resource_name = "media", data = media, schema = "https://raw.githubusercontent.com/tdwg/camtrap-dp/1.0.2/media-table-schema.json") %>%
  add_resource(resource_name = "observations", data = observations, schema = "https://raw.githubusercontent.com/tdwg/camtrap-dp/1.0.2/observations-table-schema.json") %>%
  append(c(
    profile = "https://raw.githubusercontent.com/tdwg/camtrap-dp/1.0/camtrap-dp-profile.json", # Required modified from 1.0.1 to 1.0 but no effect in .json
    name = "camtrap-dp-rodent-example-metadataset", # Required
    id = NULL,
    created = format(Sys.time(), "%Y-%m-%dT%H:%M:%SZ", tz = "UTC"), # Required
    title = "National monitoring of rodents with camera traps in Borgefjell, Norway", # Required
    description = "blablabla", # Required
    version = "1.0",
    keywords = list("small rodent", "lemming", "vole", "camera trap", "alpine tundra"),
    image = NULL,
    homepage = "https://www.nina.no/smaagnagere",
    sources = NULL,
    bibliographicCitation = "e.	Kleiven, E.F., Böhner, H., Soininen, E.M., Ims, R.A., Framstad, E., Jepsen, J. & Eide, N.E. (2025)  Camera trap based small rodent monitoring: Data from Norwegian alpine tundra",
    coordinatePrecision = NULL,
    spatial = NULL, # Required, but keep this empty, this comes later
    temporal = NULL, # Required, but keep this empty, this comes later
    taxonomic = NULL, # Required, but keep this empty, this comes later
    relatedIdentifiers = NULL,
    references = NULL
  )) %>%
  frictionless::create_package()
```

```{r}

properties$contributors <- list( #Required
  list(
    title = "Eivind Flittie Kleiven",
    firstName = "Eivind Flittie",
    lastName = "Kleiven",
    email = "eivind.kleiven@nina.no",
    path = "https://orcid.org/0000-0002-9556-0195",
    role = "principalInvestigator",
    organization = "Norwegian Institute for Nature Research (NINA)"
  ),
  list(
    title = "Hanna Böhner",
    firstName = "Hanna",
    lastName = "Böhner",
    email = "hanna.bohner@uit.no",
    path = "https://orcid.org/0000-0002-9556-0195",
    role = "contributor",
    organization = "UiT, The Arctic University of Norway"
  ),
  list(
    title = "Erik Framstad",
    firstName = "Erik",
    lastName = "Framstad",
    email = "erik.framstad@nina.no",
    role = "contributor",
    organization = "Norwegian Institute for Nature Research (NINA)"
  ),
  list(
    title = "Eeva M. Soininen",
    firstName = "Eeva M.",
    lastName = "Soininen",
    email = "eeva.soininen@uit.no",
    path = "https://orcid.org/0000-0003-4280-8350",
    role = "principalInvestigator",
    organization = "UiT, The Arctic University of Norway"
  ),
  list(
    title = "Rolf Anker Ims",
    firstName = "Rolf Anker",
    lastName = "Ims",
    email = "rolf.ims@uit.no",
    path = "https://orcid.org/0000-0002-3687-9753",
    role = "contributor",
    organization = "UiT, The Arctic University of Norway"
  ),
  list(
    title = "Nina E. Eide",
    firstName = "Nina E.",
    lastName = "Eide",
    email = "nina.eide@nina.no",
    path = "https://orcid.org/0000-0002-7645-3300",
    role = "principalInvestigator",
    organization = "Norwegian Institute for Nature Research (NINA)"
  )
)

properties$project <- list( #Required
  title = "National rodent monitoring progam, Norway",
  samplingDesign = "systematicRandom",
  captureMethod = c("activityDetection", "timeLapse"),
  individualAnimals = FALSE,
  observationLevel = c("media", "event")
)

properties$licenses <- list( #Required
  list(
    name = "CC-BY-4.0",
    path = "https://creativecommons.org/licenses/by/4.0/",
    scope = "data"
  ),
  list(
    name = "CC-BY-4.0",
    path = "https://creativecommons.org/licenses/by/4.0/",
    scope = "media"
  )
)

properties$keywords <- c("small rodent", "lemming", "vole", "camera trap", "alpine tundra")

properties$gbifIngestion <- list(observationLevel = "media")
```

# Write metadata Package

```{r}
frictionless::write_package(properties, here::here("interim"))
```

# Read with camtrapdp

This automatically updates the spatial, temporal and taxonomic coverage in the metametadata, based on the metadata.

```{r}
properties_dp <- camtrapdp::read_camtrapdp(here::here("interim", "datapackage.json"))
```

# Write Camtrap DP

```{r}
camtrapdp::write_camtrapdp(properties_dp, here::here("processed"))
```

# Fix Camtrap DP JSON errors from converstion through camtrapdp
```{r}
# Fix the schema references that got corrupted by camtrapdp processing
final_package <- jsonlite::fromJSON(here::here("processed", "datapackage.json"))

# Replace the schema arrays with simple URL strings
# The resources is a data.frame, so we access the schema column directly
final_package$resources$schema[[1]] <- "https://raw.githubusercontent.com/tdwg/camtrap-dp/1.0.2/deployments-table-schema.json"
final_package$resources$schema[[2]] <- "https://raw.githubusercontent.com/tdwg/camtrap-dp/1.0.2/media-table-schema.json"
final_package$resources$schema[[3]] <- "https://raw.githubusercontent.com/tdwg/camtrap-dp/1.0.2/observations-table-schema.json"

# Write the corrected package back to file
jsonlite::write_json(final_package, here::here("processed", "datapackage.json"), pretty = TRUE, auto_unbox = TRUE)
```

# Test writing in Dwc and EML
```{r}
rodent_dp <- camtrapdp::read_camtrapdp(here::here("processed", "datapackage.json"))
camtrapdp::write_dwc(rodent_dp, here::here("Dwc", "Interim"))
#camtrapdp::write_eml(properties_dp, here::here("Dwc_EML"))
``` 